import { useEffect, useMemo, useState } from 'react'
import { getHealth, getTrace, getTraceSummary, getTraces, runAgent } from './api/traces.js'

const typeLabels = { llm_call: 'LLM call', knowledge_base_search: 'Knowledge base', database_query: 'Database query', external_api_call: 'Order API', tool_call: 'Tool call' }
const typeIcons = { llm_call: '✦', knowledge_base_search: 'KB', database_query: '⌁', external_api_call: 'API', tool_call: '↗' }

function formatDuration(value) { return value == null || !Number.isFinite(Number(value)) ? '—' : `${value} ms` }
function formatDate(value) { if (!value) return '—'; const date = new Date(value); return Number.isNaN(date.getTime()) ? '—' : date.toLocaleString([], { dateStyle: 'medium', timeStyle: 'short' }) }
function Status({ value }) { return <span className={`status status-${value || 'unknown'}`}>{value || 'unknown'}</span> }

function App() {
  const [view, setView] = useState('dashboard'); const [traces, setTraces] = useState([]); const [selected, setSelected] = useState(null)
  const [detail, setDetail] = useState(null); const [summary, setSummary] = useState(null); const [loading, setLoading] = useState(true); const [apiOnline, setApiOnline] = useState(null)
  const [query, setQuery] = useState(''); const [filter, setFilter] = useState('all'); const [error, setError] = useState(''); const [agentInput, setAgentInput] = useState(''); const [agentResult, setAgentResult] = useState(null); const [running, setRunning] = useState(false)

  async function loadTraces() { setLoading(true); try { const data = await getTraces(); setTraces(data); setApiOnline(true) } catch (err) { setApiOnline(false); setError(err.message) } finally { setLoading(false) } }
  useEffect(() => { getHealth().then(() => setApiOnline(true)).catch(() => setApiOnline(false)); loadTraces() }, [])
  useEffect(() => { if (!selected) return; setDetail(null); Promise.all([getTrace(selected), getTraceSummary(selected)]).then(([nextDetail, nextSummary]) => { setDetail(nextDetail); setSummary(nextSummary) }).catch((err) => setError(err.message)) }, [selected])

  const filtered = useMemo(() => traces.filter((trace) => `${trace.trace_id} ${trace.input} ${trace.status}`.toLowerCase().includes(query.toLowerCase()) && (filter === 'all' || trace.status === filter)), [traces, query, filter])
  const metrics = { total: traces.length, completed: traces.filter((trace) => trace.status === 'completed').length, failed: traces.filter((trace) => trace.status === 'failed').length, running: traces.filter((trace) => trace.status === 'running').length }
  function openTrace(id) { setSelected(id); setView('detail') }
  async function submitAgent() { if (!agentInput.trim()) return; setRunning(true); setError(''); try { const result = await runAgent(agentInput); setAgentResult(result); await loadTraces() } catch (err) { setError(err.message) } finally { setRunning(false) } }

  return <div className="app-shell"><aside className="sidebar"><div className="brand"><span className="brand-mark">T</span><span>TraceLens</span></div><nav><Nav active={view === 'dashboard'} onClick={() => setView('dashboard')} icon="◈">Dashboard</Nav><Nav active={view === 'agent'} onClick={() => setView('agent')} icon="▶">Run Agent</Nav><Nav active={view === 'traces' || view === 'detail'} onClick={() => setView('traces')} icon="⌘">Traces</Nav><Nav active={view === 'architecture'} onClick={() => setView('architecture')} icon="⌘">Architecture</Nav></nav><div className="sidebar-foot"><div className={`connection-label ${apiOnline === false ? 'offline' : ''}`}><span className="pulse" /> API {apiOnline === false ? 'offline' : apiOnline ? 'connected' : 'checking'}</div><small>FastAPI · PostgreSQL</small></div></aside><main className="main-content"><header className="topbar"><div><p className="eyebrow">OPERATIONS / {view.toUpperCase()}</p><h1>{view === 'dashboard' ? 'Agent observability dashboard' : view === 'agent' ? 'Run a real agent request' : view === 'architecture' ? 'System architecture' : view === 'detail' ? 'Trace details' : 'Traces'}</h1><p className="lede">{view === 'architecture' ? 'The implementation path behind each observed execution.' : 'Follow every model, retrieval, data, and API operation in one execution view.'}</p></div><button className="refresh" onClick={loadTraces}>↻ Refresh data</button></header>{error && <div className="alert">{error}<button onClick={() => setError('')}>Dismiss</button></div>}{view === 'dashboard' && <><section className="metric-grid"><Metric label="Total traces" value={metrics.total} /><Metric label="Running" value={metrics.running} /><Metric label="Completed" value={metrics.completed} /><Metric label="Failed" value={metrics.failed} /></section><TraceTable traces={filtered} loading={loading} query={query} setQuery={setQuery} filter={filter} setFilter={setFilter} onOpen={openTrace} /></>}{view === 'traces' && <TraceTable traces={filtered} loading={loading} query={query} setQuery={setQuery} filter={filter} setFilter={setFilter} onOpen={openTrace} />}{view === 'agent' && <AgentPanel input={agentInput} setInput={setAgentInput} running={running} result={agentResult} onRun={submitAgent} onOpen={() => agentResult?.trace_id && openTrace(agentResult.trace_id)} />}{view === 'architecture' && <ArchitectureView />}{view === 'detail' && <div className="detail-page"><button className="back-button" onClick={() => setView('traces')}>← Back to traces</button><TraceDetail detail={detail} summary={summary} trace={traces.find((item) => item.trace_id === selected)} /></div>}</main></div>
}

function Nav({ active, onClick, icon, children }) { return <button className={`nav-item ${active ? 'active' : ''}`} onClick={onClick}><span>{icon}</span>{children}</button> }
function Metric({ label, value }) { return <div className="metric-card"><div className="metric-top"><span>{label}</span><i /></div><strong>{value}</strong><small>Current workspace</small></div> }
function TraceTable({ traces, loading, query, setQuery, filter, setFilter, onOpen }) { return <section className="panel trace-panel"><div className="panel-heading"><div><p className="eyebrow">TRACE EXPLORER</p><h2>Recent executions</h2></div><span className="count">{traces.length} visible</span></div><div className="filters"><div className="search">⌕<input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search traces or prompts" /></div><select value={filter} onChange={(event) => setFilter(event.target.value)}><option value="all">All statuses</option><option value="completed">Completed</option><option value="failed">Failed</option><option value="running">Running</option></select></div>{loading ? <div className="state">Loading traces...</div> : traces.length ? <div className="trace-list">{traces.map((trace) => <button className="trace-row" key={trace.trace_id} onClick={() => onOpen(trace.trace_id)}><span className="trace-main"><strong>{trace.input}</strong><small>{trace.trace_id}</small></span><Status value={trace.status} /><span className="row-meta">{trace.event_count} events</span><span className="row-meta">{formatDuration(trace.duration_ms)}</span><span className="row-date">{formatDate(trace.started_at)}</span><span>→</span></button>)}</div> : <div className="empty-state"><strong>No traces found</strong><span>Run the agent to create a real execution.</span></div>}</section> }
function AgentPanel({ input, setInput, running, result, onRun, onOpen }) { return <section className="panel agent-panel"><div className="panel-heading"><div><p className="eyebrow">AI AGENT WORKLOAD</p><h2>Execute a real agent request</h2></div></div><div className="agent-interface"><label>Message</label><textarea value={input} onChange={(event) => setInput(event.target.value)} rows="4" placeholder="Where is my order ORD-1001 and when will it arrive?" disabled={running} /><button className="agent-run-button" onClick={onRun} disabled={running || !input.trim()}>{running ? 'Running...' : '▶ Run Agent'}</button>{result && <div className={`agent-result result-${result.status}`}><div className="result-header"><strong>{result.status}</strong><span className="mode-label">{result.llm_mode === 'mock' ? 'MOCK LLM' : 'REAL LLM'}</span></div><p>{result.response}</p>{result.trace_id && <button className="view-trace-button" onClick={onOpen}>View trace →</button>}</div>}</div></section> }
function TraceDetail({ detail, summary, trace }) { if (!detail) return <section className="panel state">Loading trace...</section>; const events = detail.events || []; const categories = [['LLM', summary?.llm_duration_ms], ['Knowledge Base', summary?.knowledge_base_duration_ms], ['Database', summary?.database_duration_ms], ['External API', summary?.external_api_duration_ms], ['Tools', summary?.tool_duration_ms]]; const slowest = Math.max(...events.map((event) => event.duration_ms || 0), 0); return <section className="panel detail-panel"><div className="panel-heading"><div><p className="eyebrow">TRACE INSPECTOR</p><h2>Execution lineage</h2></div><Status value={detail.status} /></div><div className="trace-id">{detail.trace_id}</div><div className="info-grid detail-info"><Info label="Trace ID" value={detail.trace_id} /><Info label="Status" value={detail.status} /><Info label="Total Duration" value={formatDuration(detail.duration_ms)} /><Info label="Event Count" value={events.length} /><Info label="Started At" value={formatDate(trace?.started_at)} /><Info label="Completed At" value={formatDate(trace?.completed_at)} /><Info label="Request" value={detail.input} /><Info label="Response" value={detail.output} /></div><div className="section-label">Runtime events</div><div className="timeline">{events.map((event, index) => <div className="timeline-item" key={event.event_id}><div className={`event-icon event-${event.status}`}>{typeIcons[event.event_type] || '•'}</div>{index < events.length - 1 && <div className="timeline-line" />}<div className="event-content"><div className="event-title"><strong>{typeLabels[event.event_type] || event.event_type}</strong><Status value={event.status} /></div><div className="event-component">{event.component} · {formatDuration(event.duration_ms)}</div><div className="event-meta"><span>Sequence {event.sequence_number}</span><span>Parent {event.parent_event_id || 'root'}</span>{event.duration_ms === slowest && <span>Slowest</span>}</div>{(event.input_data || event.output_data || event.error_message) && <details className="event-details"><summary>Inspect payload</summary><pre>{JSON.stringify({ input: event.input_data, output: event.output_data, error: event.error_message }, null, 2)}</pre></details>}</div></div>)}</div><div className="section-label">Latency breakdown</div><div className="breakdown">{categories.map(([label, value]) => <div className="bar-row" key={label}><span>{label}</span><div className="bar"><i style={{ width: `${summary?.total_event_duration_ms ? Math.max(4, (value / summary.total_event_duration_ms) * 100) : 4}%` }} /></div><strong>{formatDuration(value)}</strong></div>)}</div></section> }
function Info({ label, value }) { return <div><small>{label}</small><strong>{value || '—'}</strong></div> }
function ArchitectureView() { return <section className="architecture-view"><div className="architecture-flow"><Node label="React frontend" detail="Dashboard and trace explorer" /><span>↓</span><Node label="FastAPI" detail="/agent/run and trace APIs" /><span>↓</span><Node label="Trace context + instrumentation" detail="ContextVars, adapters, decorators" /><span>↓</span><Node label="Customer support agent" detail="Three LLM stages, KB, DB, and HTTP client" /><div className="branch-grid"><Node label="GeminiProvider" detail="3 real LLM calls" /><Node label="KnowledgeBase" detail="Local retrieval" /><Node label="OrderService" detail="PostgreSQL" /><Node label="OrderManagementClient" detail="Real HTTP request" /></div><span>↓</span><Node label="PostgreSQL" detail="traces, trace_events, orders, customers" /></div><div className="architecture-note"><p className="eyebrow">OBSERVABILITY BOUNDARY</p><strong>Adapters record operations as they execute.</strong><span>Sequence, duration, status, payloads, and parent IDs reconstruct the runtime lineage shown in the trace inspector.</span></div></section> }
function Node({ label, detail }) { return <div className="architecture-node"><strong>{label}</strong><span>{detail}</span></div> }

export default App
